// console.log(2>1)
// console.log(2<1)
// console.log(2>=1)
// console.log(2<=1)
// console.log(2=1)
// console.log(2!=1)
console.log("2">1)
console.log("2"==2)
console.log("02">1)
console.log(null==0)
console.log(null>=0)
console.log(undefined==0)
console.log(undefined<0)
console.log(undefined>0)
// === this also check if datatype is same 
console.log("2"===2)
console.log("2"==="2")